- name: Push git commits with local variables.
  hosts: localhost
  any_errors_fatal: true
  vars:
    branch: uat
  tasks:
    - name: Set origin to include username and password.
      shell: "git remote set-url origin https://{{ username }}:{{ password }}@github.com/{{ username }}/jenkins-cicd-mongo-api.git"

    - name: display output
      shell: chmod 755 {{ tag_script }}

    - name: Generate new tag
      script: "{{ tag_script }}"
      register: out

    - name: Tag renew
      debug:
          msg: "Tag branch {{ branch }} with {{ out.stdout }}"

    - name: Set URL fact
      set_fact:
        tag: "{{ out.stdout }}"

    - name: Set tag and push
      shell: |
        git tag -a {{ tag }} -m "release OK"
        git commit . -m "UAT release OK - tagged with {{ out.stdout }}"
        git push origin {{ branch }} --follow-tags
